environment:
  matrix:
  - nodejs_version: "6"
  - nodejs_version: "8"
  - nodejs_version: "10"

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm config set spin false
  - npm install -g bower
  - npm install

# Post-install test scripts.
test_script:
  - node --version
  - npm --version
  - bower --version
  - npm test

# Don't actually build.
build: off
